name: DEPLOY

# Sur un "push" dans la branche "main"
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      
      # Rsync deploy
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --exclude="" --include="" --filter=""
          remote_path: /empty
          remote_host: ${{ secrets.HOST }}
          remote_user: dev
          remote_key: ${{ secrets.DEPLOY_KEY }}
