name: Deploy to remote server
on:
  push:
    branches: 
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      run : actions/checkout@v

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          ls
      
