name: Deploy to remote server
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Start SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
    - name: Add Auth Host
      run : ssh-add
      
    - name: Deploy code
      run: |
        ssh dev@${{ secrets.SSH_HOST }} "ls"
