name: Deploy to remote server
on:
  push:
    branches: 
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Generate keys
      run : |
        ls
        cat ~/.ssh/github_actions_rsa.pub
          
