name: Deploy to remote server
on:
  push:
    branches: 
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses : actions/checkout@v2

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }} 
        port: 22
        script: |
          ls
      
