name: Deploy to remote server
on:
  push:
    branches: 
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Start SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
    - name : Setup ssh key
      run: ssh-keys setup-ssh --ssh-private-key ${{ secrets.SSH_PRIVATE_KEY }} --ssh-public-key ${{ secrets.SSH_PUBLIC_KEY }}
      
    - name: Deploy code
      run: 
         ssh dev@${{ secrets.SSH_HOST }}
#         ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: make a ls
      run: ls       
