name: Deploy to remote server
on:
  push:
    branches: 
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Generate keys
      run : |
        ssh-keygen -t rsa -b 4096 -C "github actions key" -f ~/.ssh/github_actions_rsa
        cd /root/.ssh/
        ls
        cat github_actions_rsa
        ls
        ls
        cat github_actions_rsa.pub
          
